export interface Product {
  id: string;
  name: string;
  price: number;
  image: string;
  hoverImage?: string;
  sizes: string[];
  category: string;
  inStock: boolean;
}

export interface Team {
  id: string;
  name: string;
  slug: string;
  bannerDesktop: string;
  bannerMobile: string; 
  products: Product[];
}
export const teamsMock: Team[] = [
  {
    id: "boca",
    name: "Boca Juniors",
    slug: "boca",
    bannerDesktop: "/camisetas/Boca/banner2.jpg",
    bannerMobile: "/camisetas/Boca/banner2.jpg",
    products: [
      {
  
    id: "boca-2",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca2.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-3",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca3.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-4",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca4.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-5",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca5.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-6",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca6.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-7",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca7.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-8",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca8.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-9",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca9.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-10",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca10.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-11",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca11.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-12",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca12.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-13",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca13.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-14",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca14.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-15",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca15.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-16",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca16.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-17",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca17.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-18",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca18.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-19",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca19.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "boca-20",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/Boca/Boca20.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  }]
},
{
    id: "river",
    name: "River Plate",
    slug: "river",
    bannerMobile: "/camisetas/River/banner2.jpg",
    bannerDesktop: "/camisetas/River/banner2.jpg",
    products: [
  {
    id: "river-1",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/River/River1.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "river-2",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/River/River2.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "river-3",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/River/River3.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "river-4",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/River/River4.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "river-5",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/River/River5.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "river-6",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/River/River6.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "river-7",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/River/River7.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "river-8",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/River/River8.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "river-9",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/River/River9.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "river-10",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/River/River10.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "river-11",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/River/River11.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "river-12",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/River/River12.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "river-13",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/River/River13.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  },
  {
    id: "river-14",
    name: "Camiseta Titular",
    price: 20000,
    image: "/camisetas/River/River14.png",
    hoverImage: "",
    sizes: ["S", "M", "L", "XL"],
    category: "Camisetas",
    inStock: true,
  }
]
},
{
    id: "argentina",
    name: "Argentina",
    slug: "argentina",
    bannerMobile: "/camisetas/Argentina/banner1.jpg",
    bannerDesktop: "/camisetas/Argentina/banner2.jpg",
    products: [
      {
        id: "argentina-1",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina1.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-2",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina2.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-3",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina3.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-4",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina4.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-5",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina5.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-6",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina6.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-7",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina7.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-8",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina8.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-9",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina9.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-10",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina10.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-11",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina11.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-12",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina12.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-13",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina13.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-14",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina14.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-15",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina15.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-16",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina16.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-17",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina17.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-18",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina18.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "argentina-19",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Argentina/Argentina19.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      }
    ]
  },
{
    id: "estudiantes",
    name: "Estudiantes",
    slug: "estudiantes",
    bannerMobile: "/camisetas/Estudiantes/banner2.jpg",
    bannerDesktop: "/camisetas/Estudiantes/banner2.jpg",
    products: [
      {
        id: "estudiantes-1",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Estudiantes/Estudiantes1.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "estudiantes-2",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Estudiantes/Estudiantes2.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "estudiantes-3",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Estudiantes/Estudiantes3.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "estudiantes-4",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Estudiantes/Estudiantes4.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "estudiantes-5",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Estudiantes/Estudiantes5.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "estudiantes-6",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Estudiantes/Estudiantes6.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "estudiantes-7",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Estudiantes/Estudiantes7.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      }
    ]
  },
  {
    id: "gimnasia",
    name: "Gimnasia",
    slug: "gimnasia",
    bannerMobile: "/camisetas/Gimnasia/banner2.jpg",
    bannerDesktop: "/camisetas/Gimnasia/banner2.jpg",
    products: [
      {
        id: "gimnasia-1",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Gimnasia/Gimnasia1.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "gimnasia-2",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Gimnasia/Gimnasia2.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "gimnasia-3",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Gimnasia/Gimnasia3.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "gimnasia-4",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Gimnasia/Gimnasia4.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      }
    ]
  },
  {
    id: "huracan",
    name: "Huracán",
    slug: "huracan",
    bannerMobile: "/camisetas/Huracan/banner1.jpg",
    bannerDesktop: "/camisetas/Huracan/banner2.jpg",
    products: [
      {
        id: "huracan-1",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Huracan/Huracan1.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "huracan-2",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Huracan/Huracan2.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "huracan-3",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Huracan/Huracan3.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "huracan-4",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Huracan/Huracan4.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      }
    ]
  },
  {
    id: "independiente",
    name: "Independiente",
    slug: "independiente",
    bannerMobile: "/camisetas/Independiente/banner2.jpg",
    bannerDesktop: "/camisetas/Independiente/banner2.jpg",
    products: [
      {
        id: "independiente-1",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente1.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-2",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente2.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-3",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente3.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-4",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente4.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-5",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente5.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-6",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente6.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-7",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente7.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-8",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente8.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-9",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente9.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-10",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente10.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-11",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente11.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-12",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente12.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-13",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente13.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-14",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente14.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-15",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente15.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-16",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente16.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-17",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente17.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-18",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente18.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-19",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente19.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "independiente-20",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Independiente/Independiente20.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      }
    ]
  },
  {
    id: "racing",
    name: "Racing",
    slug: "racing",
    bannerMobile: "/camisetas/Racing/banner2.jpg",
    bannerDesktop: "/camisetas/Racing/banner2.jpg",
    products: [
      {
        id: "racing-1",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Racing/Racing1.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "racing-2",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Racing/Racing2.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "racing-3",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Racing/Racing3.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "racing-4",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Racing/Racing4.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "racing-5",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Racing/Racing5.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "racing-6",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Racing/Racing6.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "racing-7",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Racing/Racing7.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "racing-8",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Racing/Racing8.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "racing-9",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Racing/Racing9.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "racing-10",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Racing/Racing10.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "racing-11",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Racing/Racing11.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "racing-12",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Racing/Racing12.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "racing-13",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Racing/Racing13.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      }
    ]
  },
  {
    id: "san-lorenzo",
    name: "San Lorenzo",
    slug: "san-lorenzo",
    bannerMobile: "/camisetas/San Lorenzo/banner2.jpg",
    bannerDesktop: "/camisetas/San Lorenzo/banner2.jpg",
    products: [
      {
        id: "san-lorenzo-1",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/San Lorenzo/San Lorenzo1.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "san-lorenzo-2",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/San Lorenzo/San Lorenzo2.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "san-lorenzo-3",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/San Lorenzo/San Lorenzo3.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "san-lorenzo-4",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/San Lorenzo/San Lorenzo4.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "san-lorenzo-5",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/San Lorenzo/San Lorenzo5.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "san-lorenzo-6",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/San Lorenzo/San Lorenzo6.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "san-lorenzo-7",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/San Lorenzo/San Lorenzo7.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "san-lorenzo-8",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/San Lorenzo/San Lorenzo8.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "san-lorenzo-9",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/San Lorenzo/San Lorenzo9.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "san-lorenzo-10",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/San Lorenzo/San Lorenzo10.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "san-lorenzo-11",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/San Lorenzo/San Lorenzo11.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "san-lorenzo-12",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/San Lorenzo/San Lorenzo12.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "san-lorenzo-13",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/San Lorenzo/San Lorenzo13.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "san-lorenzo-14",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/San Lorenzo/San Lorenzo14.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "san-lorenzo-15",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/San Lorenzo/San Lorenzo15.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "san-lorenzo-16",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/San Lorenzo/San Lorenzo16.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      }
    ]
  },
  {
    id: "velez",
    name: "Vélez Sarsfield",
    slug: "velez",
    bannerMobile: "/camisetas/Velez/banner1.jpg",
    bannerDesktop: "/camisetas/Velez/banner1.jpg",
    products: [
      {
        id: "velez-1",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Velez/Velez1.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      },
      {
        id: "velez-2",
        name: "Camiseta Titular",
        price: 20000,
        image: "/camisetas/Velez/Velez2.png",
        hoverImage: "",
        sizes: ["S", "M", "L", "XL"],
        category: "Camisetas",
        inStock: true,
      }
    ]
  }
];